function main() {
    document.getElementById("main").innerHTML = '<div id="main" align="center" class="blur" style="border: ridge #000000 5px;"> <h1 style="color:DARKRED">Rust Server Creator</h1> <h2 style="color: DARKBLUE">by x04000</h2> <p></p> <p></p> <h3 style="color:BLACK"><b>A Free & Friendly Server Creator</b><p>Not affiliated with Facepunch, this is a Unofficial Server Creator</p></h3> <p></p> <img src="assets/none.png" width="10px"> <p></p> <img src="assets/download2.png" width="200px" onclick="download()"> <p></p> <img src="assets/rusticonbig.png" width="480px"></div>';
}
function about() {
    document.getElementById("main").innerHTML = '<div id="main" align="center" class="blur" style="border: ridge #000000 5px;"> <h1 style="color:DARKRED">Rust Server Creator</h1> <h2 style="color: DARKBLUE">by x04000</h2> <p></p> <p></p> <h3 style="color:BLACK">Rust Server Creator (RSC) is an Open Source project to make server more easier</h3> <h3 style="color:BLACK">The code are witted in C# and the server base is SteamCMD (from Valve)</h3> <h3 style="color:BLACK">RSC Support plugins with Oxide Mod (from uMod)</h3> <p></p> <img src="assets/none.png" width="10px"> <p></p> <h2 style="color:BLACK">Most regular issues</h2> <h3 style="color:rgb(27, 27, 158)">If the UI and text of the program sometimes crash or glitch, try to install the text fonts (they are in RSC\[Rust/Valorant]_Font.ttf)</h3> <h3 style="color:rgb(27, 27, 158)">If you have problems during the installation of SteamCMD or Oxide Mods, maybe you need to disable the antivirus (after the installation activate it again)</h3> <h3 style="color:rgb(27, 27, 158)">RSC it`s sometimes detected by the antivirus, this is because RSC it`s a fan project</h3> <p></p> <img src="assets/rusticonbig.png" width="480px"></div>';
}
function download() {
    document.getElementById("main").innerHTML = '<div id="main" align="center" class="blur" style="border: ridge #000000 5px;"> <h1 style="color:DARKRED">Rust Server Creator</h1> <h2 style="color: DARKBLUE">by x04000</h2> <p></p> <p></p> <h3 style="color:BLACK"><b>A Free & Friendly Server Creator</b><p>Not affiliated with Facepunch, this is a Unofficial Server Creator</p></h3> <p></p> <img src="assets/none.png" width="10px"> <p></p> <a href="https://github.com/x04000/Rust-Server-Creator"><img src="assets/source.png" width="250px"></a> <p></p> <a href="https://github.com/x04000/Rust-Server-Creator/releases/download/v.1.2.2.3/RSC.exe"><img src="assets/download.png" width="200px"></a> <p></p> <img src="assets/rusticonbig.png" width="420px"></div>';
}
function patchnotes() {
    document.getElementById("main").innerHTML = '<div id="main" align="center" class="blur" style="border: ridge #000000 5px;"> <h1 style="color:DARKRED">Rust Server Creator</h1> <h2 style="color: DARKBLUE">by x04000</h2> <p></p> <img src="assets/none.png" width="10px"> <p></p> <h3 style="color:BLACK"><b>Patch Notes</b></h3> <p></p> <p style="color:darkslateblue"><b>v.1.2.2.3</b></p> <p style="color:white">[+] SteamCMD Downloader fixed</p> <p style="color:white">[+] SteamCMD Installer fixed</p> <p style="color:white">[-] Correction of bugs</p> <p style="color:white"></p> <p style="color:darkslateblue"><b>v.1.2.2.2</b></p> <p style="color:white">[+] Font bug fixed</p> <p style="color:white"></p> <p style="color:darkslateblue"><b>v.1.2.2.1</b></p> <p style="color:white">[+] Updater Fully Fixed</p> <p style="color:white">[+] Version Bug Fixed</p> <p style="color:white"></p> <p style="color:darkslateblue"><b>v.1.2.2</b></p> <p style="color:white">[+] New section (Release Notes)</p> <p style="color:white">[+] New function (Open Plugin Config)</p> <p style="color:white">[+] Wipe warning</p> <p style="color:white"></p>[+] Updater Fixed</p> <p style="color:white">[-] Correction of bugs</p> <p></p> <img src="assets/rusticonbig.png" width="480px"></div>';
}